"""
THERMO-PLUME — Layer 1.5, Step 3: Export Model to C Code
============================================================

WHAT THIS FILE DOES (in plain words):
--------------------------------------
Our trained Decision Tree currently only exists as a Python object
(model.joblib). A real ESP32 microcontroller cannot run Python — it
needs plain C code.

This script reads the trained tree's internal structure (every yes/no
question it learned, like "is co2 <= 917.5?") and automatically writes
out an equivalent C function. This is a real, working demonstration of
"TinyML deployment," not just a claim in a slide.

HOW A DECISION TREE IS STORED INTERNALLY:
--------------------------------------------
scikit-learn stores a trained tree as arrays describing each node:
  - which FEATURE that node checks (e.g. feature index 2 = "co2")
  - what THRESHOLD it compares against (e.g. 917.5)
  - which node to go to if the answer is "yes" (left child)
  - which node to go to if the answer is "no" (right child)
  - if it's a "leaf" (an ending point), which CLASS it predicts

This script walks that structure and turns it into nested C if/else
statements — exactly what you'd flash onto an ESP32.

HOW TO USE THIS FILE:
----------------------
    python3 export_to_c.py

This creates thermoplume_model.c and prints the file size, so you can
quote a real number like "our model is 1.8 KB, deployment-ready."
"""

import joblib
import os
from sklearn.tree import _tree

FEATURE_COLUMNS = ["pm25", "pm10", "co2", "humidity", "temperature", "voc_reported"]
CLASS_NAMES = ["NORMAL", "RISING_RISK", "STAGNATION_PREDICTED"]


def tree_to_c_code(tree_model, feature_names, class_names):
    """
    Walks the trained sklearn tree and builds a string of C code that
    represents the exact same decision logic as nested if/else blocks.
    """
    tree_ = tree_model.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]

    lines = []
    lines.append("// AUTO-GENERATED by export_to_c.py — DO NOT EDIT BY HAND")
    lines.append("// This is the THERMO-PLUME Edge Sensing Node classifier,")
    lines.append("// converted from a trained scikit-learn Decision Tree.")
    lines.append("// Deployment target: ESP32 / ARM Cortex-M (TinyML inference)")
    lines.append("")
    lines.append("// Class labels (integer codes returned by the function):")
    for i, cname in enumerate(class_names):
        lines.append(f"//   {i} = {cname}")
    lines.append("")
    lines.append("int classify_air_quality(float pm25, float pm10, float co2, "
                  "float humidity, float temperature, float voc_reported) {")

    def recurse(node, depth):
        indent = "    " * (depth + 1)
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            # This is a decision node (an if/else question)
            name = feature_name[node]
            threshold = tree_.threshold[node]
            lines.append(f"{indent}if ({name} <= {threshold:.4f}f) {{")
            recurse(tree_.children_left[node], depth + 1)
            lines.append(f"{indent}}} else {{")
            recurse(tree_.children_right[node], depth + 1)
            lines.append(f"{indent}}}")
        else:
            # This is a leaf node (a final answer)
            # tree_.value[node] holds how many training examples of each
            # class ended up here; the class with the most examples wins.
            class_counts = tree_.value[node][0]
            predicted_class = int(class_counts.argmax())
            lines.append(f"{indent}return {predicted_class}; // {class_names[predicted_class]}")

    recurse(0, 0)
    lines.append("}")
    return "\n".join(lines)


def export():
    model = joblib.load("model.joblib")
    c_code = tree_to_c_code(model, FEATURE_COLUMNS, CLASS_NAMES)

    output_path = "thermoplume_model.c"
    with open(output_path, "w") as f:
        f.write(c_code)

    file_size_bytes = os.path.getsize(output_path)
    print(f"Exported C model to {output_path}")
    print(f"File size: {file_size_bytes} bytes ({file_size_bytes / 1024:.2f} KB)")
    print(f"Tree depth: {model.get_depth()}  |  Decision nodes: {model.tree_.node_count}")
    print("\nThis file can be compiled directly into an ESP32/Arduino firmware project.")
    print("It has ZERO external dependencies — no TensorFlow, no libraries — just plain C.")


if __name__ == "__main__":
    export()
