// AUTO-GENERATED by export_to_c.py — DO NOT EDIT BY HAND
// This is the THERMO-PLUME Edge Sensing Node classifier,
// converted from a trained scikit-learn Decision Tree.
// Deployment target: ESP32 / ARM Cortex-M (TinyML inference)

// Class labels (integer codes returned by the function):
//   0 = NORMAL
//   1 = RISING_RISK
//   2 = STAGNATION_PREDICTED

int classify_air_quality(float pm25, float pm10, float co2, float humidity, float temperature, float voc_reported) {
    if (pm10 <= 50.0050f) {
        if (pm25 <= 35.0050f) {
            return 0; // NORMAL
        } else {
            return 1; // RISING_RISK
        }
    } else {
        if (co2 <= 1000.0050f) {
            if (voc_reported <= 417.6150f) {
                if (voc_reported <= 401.2550f) {
                    return 1; // RISING_RISK
                } else {
                    if (humidity <= 46.3500f) {
                        return 2; // STAGNATION_PREDICTED
                    } else {
                        return 1; // RISING_RISK
                    }
                }
            } else {
                return 2; // STAGNATION_PREDICTED
            }
        } else {
            if (pm25 <= 35.1300f) {
                return 1; // RISING_RISK
            } else {
                return 2; // STAGNATION_PREDICTED
            }
        }
    }
}